language: rust

rust:
  - stable
  - beta
  - nightly

os: 
  - linux

dist: bionic

before_script:
    - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)

script:
    - cargo build --verbose
    - cargo tarpaulin --out Xml
    - bash <(curl -s https://codecov.io/bash)
