language: rust

rust:
  - stable
  - beta
  - nightly

os: 
  - linux

dist: bionic

script:
    - cargo install cargo-tarpaulin
    - cargo build --verbose
    - cargo tarpaulin --out Xml
    - bash <(curl -s https://codecov.io/bash)
